
http:
  max-conn-per-route: 20
  max-conn-total: 200
  connect-timeout: 5000
  socket-timeout: 6000
  header:
    Content-Type: application/x-www-form-urlencoded
    Accept: application/xml
    Charset: UTF-8
server:
  uri: https:XXXXXXXXX
  MD5Key: XXXXXXXX
  merchantId: '00000000035349'
  version: 2.0
  signType: MD5
  filePath: ./${server.merchantId}/
  duck: 1111
  port: 8081
spring:
  profiles:
    active: prod

---
server:
  port: 8082
spring:
  profiles: dev
---
server:
  port: 8083
spring:
  profiles: prod
